on:
  workflow_call:
    inputs:
      dockerfile-path:
        required: false
        type: string
        default: '.'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v3
      
    - name: Build
      run: |
        cd "${{ inputs.dockerfile-path }}"
        docker build -t ghcr.io/${GITHUB_REPOSITORY,,}:$(date +%Y%m%d.$GITHUB_RUN_NUMBER) .
          
    - name: Log into registry 
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  
        
    - name: Publish
      run: |
        docker push ghcr.io/${GITHUB_REPOSITORY,,}:$(date +%Y%m%d.$GITHUB_RUN_NUMBER)